apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:036043092806:certificate/f0567ee9-44b0-4686-9885-cdaed6d7d50b"
    alb.ingress.kubernetes.io/inbound-cidrs: "210.94.41.89/32,106.254.235.234/32"
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    external-dns.alpha.kubernetes.io/aws-weight: "50"
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.clusterName | quote }}
spec:
  ingressClassName: alb
  rules:
    # 🌟 3. 지정하신 커스텀 도메인으로 들어오는 트래픽만 허용
    - host: demo.dev.swalletopscenter.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                # ALB에서 SSL(HTTPS)을 해제(Termination)하고, 파드로는 80 포트로 트래픽을 보냅니다.
                port:
                  number: 80